import { expect, type Page } from '@playwright/test'
import { createBdd } from 'playwright-bdd'
const { Given, When, Then, Before, After } = createBdd()
const browserErrors = new WeakMap<Page, string[]>()
After(async ({ page }) => { expect(browserErrors.get(page) ?? []).toEqual([]) })
Before(async ({ page }) => { browserErrors.set(page, []); page.on('pageerror', error => browserErrors.get(page)?.push(error.message)); page.on('requestfailed', request => console.error('REQUEST FAILED', request.url(), request.failure()?.errorText)); page.on('pageerror', error => console.error('BROWSER ERROR', error.message)); page.on('console', message => { if (message.type() === 'error' || message.type() === 'warning') console.log('BROWSER', message.text()) }) })
Given('I open the knowledge library', async ({ page }) => { await page.goto('./'); await expect(page.getByRole('heading', { name: 'Gute Ideen. Neue Verbindungen.' })).toBeVisible(); await page.screenshot({ path: '.audit/screenshots/desktop.png' }) })
Given('I open the knowledge graph', async ({ page }) => { await page.goto('./graph') })
When('I open the note {string}', async ({ page }, title: string) => { await page.locator('main').getByRole('link').filter({ has: page.getByRole('heading', { name: title, exact: true }) }).click() })
Then('I see the article {string}', async ({ page }, title: string) => { await expect(page.getByRole('article').getByRole('heading', { level: 1, name: title, exact: true })).toBeVisible() })
Then('I see the insight {string}', async ({ page }, title: string) => { await expect(page.locator('.insight-block').getByText(title, { exact: true })).toBeVisible() })
When('I follow the article link {string}', async ({ page }, title: string) => { await page.locator('.prose').getByRole('link', { name: title, exact: true }).click() })
Then('I see backlinks to this note', async ({ page }) => { await expect(page.getByRole('heading', { name: 'Hier kommt der Gedanke vor' })).toBeVisible(); await expect(page.locator('.backlinks').getByRole('link').first()).toBeVisible() })
When('I search for {string}', async ({ page }, query: string) => {
  if (!await page.getByRole('dialog').isVisible()) await page.getByRole('button', { name: /Gedanken finden/ }).click()
  await page.getByRole('textbox', { name: 'Dein Wissen durchsuchen' }).fill(query)
})
Then('I find the note {string}', async ({ page }, title: string) => { await expect(page.getByRole('dialog').getByRole('link').filter({ hasText: title })).toBeVisible() })
Then('I see an empty search result', async ({ page }) => { await expect(page.getByText('Keine Notizen gefunden. Versuche einen anderen Begriff.')).toBeVisible() })
Then('I see the interactive graph', async ({ page }) => { await expect(page.getByRole('img', { name: /Interaktiver Wissensgraph/ })).toBeVisible(); await expect(page.locator('.full-graph canvas')).toBeVisible() })
When('I filter the graph to {string}', async ({ page }, filter: string) => { await page.getByRole('group', { name: 'Graph filtern' }).getByRole('button', { name: filter, exact: true }).click() })
Then('the graph list contains only topics', async ({ page }) => { const list = page.getByRole('list', { name: 'Seiten im Graphen' }); await expect(list.getByRole('listitem')).toHaveCount(6); await expect(list.locator('[data-kind="source"]')).toHaveCount(0) })
When('I open a note from the graph list', async ({ page }) => { await page.getByRole('list', { name: 'Seiten im Graphen' }).getByRole('link').first().click() })
Then('I see an article', async ({ page }) => { await expect(page.getByRole('article').getByRole('heading', { level: 1 })).toBeVisible() })
Given('the complete wiki is available offline', async ({ page }) => { await expect(page.getByText('Offline verfügbar', { exact: true })).toBeVisible({ timeout: 30000 }); await page.evaluate(async () => { await navigator.serviceWorker.ready; if (!navigator.serviceWorker.controller) await new Promise<void>(resolve => navigator.serviceWorker.addEventListener('controllerchange', () => resolve(), { once: true })) }) })
When('I disconnect from the network and reload', async ({ page, context }) => { await context.setOffline(true); await page.reload() })
Then('I see the knowledge library', async ({ page }) => { await expect(page.getByRole('heading', { name: 'Gute Ideen. Neue Verbindungen.' })).toBeVisible() })
When('I use a small screen', async ({ page }) => { await page.setViewportSize({ width: 390, height: 844 }) })
Then('the library fits the screen', async ({ page, browserName }) => {
  await expect(page.getByRole('heading', { name: 'Gute Ideen. Neue Verbindungen.' })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.screenshot({ path: `.audit/screenshots/${browserName}-mobile.png`, fullPage: true })
})
When('I open the mobile menu', async ({ page }) => { await page.getByRole('button', { name: 'Menü ☰' }).click(); await expect(page.getByRole('button', { name: /Gedanken finden/ })).toBeVisible() })
Given('I open an unknown note', async ({ page }) => { const response = await page.goto('./notes/does-not-exist'); expect(response?.status()).toBe(404) })
Then('I see a not found response', async ({ page }) => { await expect(page.getByText('Not found', { exact: true })).toBeVisible() })

When('I select the search result {string}', async ({ page }, title: string) => { await page.getByRole('dialog').getByRole('link').filter({ hasText: title }).click(); await expect(page.getByRole('dialog')).not.toBeVisible() })
When('I open the graph from navigation', async ({ page }) => { await page.getByRole('navigation', { name: 'Hauptnavigation' }).getByRole('link', { name: /Wissensgraph/ }).click() })
Then('I can copy the page link', async ({ page, context, browserName }) => { if (browserName === 'chromium') await context.grantPermissions(['clipboard-read', 'clipboard-write']); await page.getByRole('button', { name: /Link kopieren$/ }).click(); await expect(page.getByRole('status')).toHaveText('Link kopiert'); if (browserName === 'chromium') expect(await page.evaluate(() => navigator.clipboard.readText())).toBe(page.url()) })
Then('the dark design is active', async ({ page }) => {
  await expect(page.getByRole('button', { name: 'Helles Design aktivieren' })).toBeVisible()
  await expect(page.locator('body')).toHaveCSS('background-color', 'rgb(25, 27, 25)')
  await page.screenshot({ path: '.audit/screenshots/dark-desktop.png' })
})
Then('the light design is active', async ({ page }) => {
  await expect(page.getByRole('button', { name: 'Dunkles Design aktivieren' })).toBeVisible()
  await expect(page.locator('body')).toHaveCSS('background-color', 'rgb(250, 249, 245)')
})
When('I activate the light design', async ({ page }) => { await page.getByRole('button', { name: 'Helles Design aktivieren' }).click() })
When('I activate the dark design', async ({ page }) => { await page.getByRole('button', { name: 'Dunkles Design aktivieren' }).click() })
When('I reload the page', async ({ page }) => { await page.reload() })
When('I choose English', async ({ page }) => { await page.getByRole('combobox', { name: 'Sprache / Language' }).selectOption('en') })
When('I choose German', async ({ page }) => { await page.getByRole('combobox', { name: 'Sprache / Language' }).selectOption('de') })
Then('the interface is English', async ({ page }) => {
  await expect(page.locator('html')).toHaveAttribute('lang', 'en')
  await expect(page.getByRole('heading', { name: 'Good ideas. New connections.' })).toBeVisible()
  await expect(page.getByRole('button', { name: /Find a thought/ })).toBeVisible()
  await page.screenshot({ path: '.audit/screenshots/english-desktop.png' })
})
Then('the article interface is English and the note stays German', async ({ page }) => {
  await expect(page.locator('html')).toHaveAttribute('lang', 'en')
  await expect(page.getByRole('heading', { name: 'Where this thought appears' })).toBeVisible()
  await expect(page.getByText('Reading time', { exact: true })).toBeVisible()
  await expect(page.locator('.article-description')).toHaveText('Abhängigkeiten sichtbar machen, damit Verhalten nachvollziehbar und prüfbar bleibt.')
  await expect(page.getByRole('button', { name: /Copy link$/ })).toBeVisible()
  await expect(page.getByRole('combobox', { name: 'Sprache / Language' })).toHaveValue('en')
})
Then('the article interface is German', async ({ page }) => {
  await expect(page.locator('html')).toHaveAttribute('lang', 'de')
  await expect(page.getByRole('heading', { name: 'Hier kommt der Gedanke vor' })).toBeVisible()
})
When('I filter resources to {string}', async ({ page }, label: string) => { await page.getByRole('group', { name: 'Ressourcenarten' }).getByRole('button', { name: new RegExp(`^${label}`) }).click() })
Then('I see three documentation resources', async ({ page }) => {
  await expect(page.locator('.note-grid .note-card')).toHaveCount(3)
  for (const card of await page.locator('.note-grid .note-card').all()) await expect(card.locator('.card-top')).toContainText('Dokumentation')
  await page.locator('.library-feed').scrollIntoViewIfNeeded()
  await page.screenshot({ path: '.audit/screenshots/resource-types.png' })
})
Then('the article identifies a documentation resource', async ({ page }) => { await expect(page.locator('.article-header > .eyebrow')).toContainText('Dokumentation'); await expect(page.getByRole('link', { name: /Originalquelle öffnen/ })).toHaveAttribute('href', 'https://comark.dev/rendering/vue') })
Then('I see an empty resource category', async ({ page }) => { await expect(page.getByRole('status')).toContainText('Hier sind noch keine Ressourcen dieser Art.'); await expect(page.locator('.note-grid .note-card')).toHaveCount(0) })
When('I show all resources', async ({ page }) => { await page.getByRole('button', { name: /Alle Ressourcen anzeigen/ }).click() })
Then('I see four source resources', async ({ page }) => { await expect(page.locator('.note-grid .note-card')).toHaveCount(4) })
When('I filter the library to topics', async ({ page }) => { await page.getByRole('group', { name: 'Bibliothek filtern' }).getByRole('button', { name: /^Themen/ }).click() })
Then('I see six topics without resource filters', async ({ page }) => { await expect(page.locator('.note-grid .note-card')).toHaveCount(6); await expect(page.getByRole('group', { name: 'Ressourcenarten' })).not.toBeVisible() })
When('I open the search dialog using the keyboard', async ({ page }) => {
  await page.getByRole('button', { name: /Gedanken finden/ }).focus()
  await page.keyboard.press('ControlOrMeta+k')
  await expect(page.getByRole('textbox', { name: 'Dein Wissen durchsuchen' })).toBeFocused()
})
Then('focus stays inside the search dialog', async ({ page }) => {
  const dialog = page.getByRole('dialog')
  await expect(dialog).toBeVisible()
  await page.screenshot({ path: '.audit/screenshots/ui-dialog.png' })
  await dialog.getByRole('link').last().focus()
  await page.keyboard.press('Tab')
  await expect(dialog.getByRole('button', { name: 'Suche schließen' })).toBeFocused()
  await page.keyboard.press('Shift+Tab')
  await expect(dialog.getByRole('link').last()).toBeFocused()
})
When('I dismiss the search dialog with Escape', async ({ page }) => { await page.keyboard.press('Escape'); await expect(page.getByRole('dialog')).not.toBeVisible() })
Then('focus returns to the search trigger', async ({ page }) => { await expect(page.getByRole('button', { name: /Gedanken finden/ })).toBeFocused() })
